### ISSUE TITLE
[FR] automation

### ISSUE THREAD

**Issue by ciechompl** [perara/ha_systemair#3]
It is not an issue but rather request :) or maybe just a need for explanation.

I would like to make some automation with systemair. For now it is really simple: 
- temperature outside (incoming air) lower than inside my house -> fan set to high 
- temperature outside (incoming air) higher than inside my house -> fan set to low

Is is possible to make it somehow with current component ?

If not, are you able to create/develop e.g. a "service" in which we can call a specific preset eg. "manual" with given fan speed, or "auto" or any other preset.

**Comment by perara** [comment]
This should be possible already I think.
Atleast:
* You should be able to control the fan settings etc with automation. This should be universal for any device in HA.
* Im not 100% sure if you have access to variables such as temperature .etc, but this would be possible when I get time to add the sensors component (which holds all of the variables sent from the device)

**Comment by ciechompl** [comment]
got it :) ... so it can be done via standard services climate.set_* :)  haven't thought about it that your component is represented in HA as standard climate entity. cool thx
